### PR TITLE
 Fixed number_format for thousands separator

### PR DESCRIPTION
**Pull request by Marvin-Magmodules**

### CODE REVIEW

**Comment by willemstuursma** [comment]
Hi @Marvin-Magmodules! Did you consider shops in JPY / ISK? 

You should add a dependency on `moneyphp/money` maybe and get the number of decimals of each currency there, or maybe Magento provides such as functionality by default.

**Comment by Marvin-Magmodules** [comment]
@willemstuursma no, did not consider these currencies, let me check this. Is there any documentation about the currencies and decimals Mollie supports? Magento has some functions for this, but need to validate this with the API.

**Comment by Smitsel** [comment]
Hi @Marvin-Magmodules,

We have this documentation here:
https://docs.mollie.com/guides/multicurrency

**Comment by Marvin-Magmodules** [comment]
@willemstuursma can you double check "Israeli new shekel" (ILS) for me, as I'm only able to get this method when using two decimal points? ("value":"64.00","currency":"ILS")

**Pull request closed without merging**
